# Generated by Django 4.2.20 on 2025-04-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesstquestionanswer',
            name='test_aswer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.testquestion'),
            preserve_default=False,
        ),
    ]
