# Generated by Django 4.2.20 on 2025-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_tesstquestionanswer_test_aswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
