# Generated by Django 4.2.20 on 2025-05-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='coursefile',
            name='sub_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursesubtitle'),
        ),
    ]
