# Generated by Django 4.2.20 on 2025-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursesubtitle_coursefile_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubtitle',
            name='ordered',
            field=models.IntegerField(null=True),
        ),
    ]
