# Generated by Django 4.2.20 on 2025-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursesubtitle_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='ordered',
            field=models.IntegerField(null=True),
        ),
    ]
