# Generated by Django 4.2.20 on 2025-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursefile_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
