# Generated by Django 4.2.20 on 2025-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='ordered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testsub',
            name='ordered',
            field=models.IntegerField(null=True),
        ),
    ]
