# Generated by Django 4.2.20 on 2025-05-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_testquestion_ordered_testsub_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='statususercourse',
            name='is_for_action_amdin',
            field=models.IntegerField(null=True),
        ),
    ]
