# Generated by Django 4.2.20 on 2025-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_company_user_fio_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
