# Generated by Django 4.2.20 on 2025-05-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_user_user_syst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesstquestionanswer',
            name='is_true',
            field=models.IntegerField(default=0),
        ),
    ]
