# Generated by Django 4.2.20 on 2025-09-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_tesstquestionanswer_is_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_inter_site',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
