# Generated by Django 4.2.20 on 2025-09-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_user_is_inter_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResultTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_result', models.DateField(null=True)),
                ('result', models.FloatField(null=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.user')),
            ],
        ),
    ]
